// Copyright(C) 2026 Simon Weston
// Licensed under the GNU General Public License v3.0
// SPDX-License-Identifier: GPL-3.0-only
using System.Text.Json.Serialization;

namespace GrafaMon.Infrastructure.Dtos
{
    /// <summary>
    /// DTO representing a Grafana alert from the Alertmanager API.
    /// All properties are nullable to handle varying JSON shapes.
    /// </summary>
    internal sealed class GrafanaAlertDto
    {
        [JsonPropertyName("annotations")]
        public AnnotationsDto? Annotations { get; set; }

        [JsonPropertyName("endsAt")]
        public string? EndsAt { get; set; }

        [JsonPropertyName("fingerprint")]
        public string? Fingerprint { get; set; }

        [JsonPropertyName("receivers")]
        public List<ReceiverDto>? Receivers { get; set; }

        [JsonPropertyName("startsAt")]
        public string? StartsAt { get; set; }

        [JsonPropertyName("status")]
        public StatusDto? Status { get; set; }

        [JsonPropertyName("updatedAt")]
        public string? UpdatedAt { get; set; }

        [JsonPropertyName("generatorURL")]
        public string? GeneratorUrl { get; set; }

        [JsonPropertyName("labels")]
        public LabelsDto? Labels { get; set; }
    }

    internal sealed class AnnotationsDto
    {
        [JsonPropertyName("__orgId__")]
        public string? OrgId { get; set; }

        [JsonPropertyName("__value_string__")]
        public string? ValueString { get; set; }

        [JsonPropertyName("__values__")]
        public string? Values { get; set; }

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("summary")]
        public string? Summary { get; set; }
    }

    internal sealed class ReceiverDto
    {
        [JsonPropertyName("name")]
        public string? Name { get; set; }
    }

    internal sealed class StatusDto
    {
        [JsonPropertyName("inhibitedBy")]
        public List<string>? InhibitedBy { get; set; }

        [JsonPropertyName("silencedBy")]
        public List<string>? SilencedBy { get; set; }

        [JsonPropertyName("state")]
        public string? State { get; set; }
    }

    internal sealed class LabelsDto
    {
        [JsonPropertyName("__alert_rule_uid__")]
        public string? AlertRuleUid { get; set; }

        [JsonPropertyName("__grafana_autogenerated__")]
        public string? GrafanaAutogenerated { get; set; }

        [JsonPropertyName("__grafana_receiver__")]
        public string? GrafanaReceiver { get; set; }

        [JsonPropertyName("alertname")]
        public string? AlertName { get; set; }

        [JsonPropertyName("env")]
        public string? Environment { get; set; }

        [JsonPropertyName("grafana_folder")]
        public string? GrafanaFolder { get; set; }

        [JsonPropertyName("host")]
        public string? Host { get; set; }

        [JsonPropertyName("instance")]
        public string? Instance { get; set; }

        [JsonPropertyName("service_name")]
        public string? ServiceName { get; set; }

        [JsonPropertyName("severity")]
        public string? Severity { get; set; }
    }
}